name: Typeorm UML
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          CI: true
      - name: Build project
        run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout typeorm-uml
        uses: actions/checkout@v2
      - name: Checkout typeorm/typescript-example
        uses: actions/checkout@v2
        with:
          repository: typeorm/typescript-example
          path: example
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies and build typeorm-uml
        run: |
          npm ci --ignore-scripts
          npm run build
        env:
          CI: true
      - name: Install dependencies and build typeorm/typescript-example
        working-directory: example
        run: |
          npm i
          npx tsc
      - name: Test uml diagram
        working-directory: example
        run: test "$(../bin/run)" = "$EXPECTED"
        env:
          EXPECTED: http://www.plantuml.com/plantuml/png/ZLFTIyCm47_FNt4Yo0gEeR0NAMLppeyN7yOGtoHjRcjecol9ZMqu_tVJrCqo9veyzNvVTpawSYmjhwfIY3E52sqGwWAtlKq4SPh46PLaR-waBHweL6Xcf9BumXEIU12m13Rn84qEuiLUt2hFn-7yq1pulh2gJ5SnlM-kLrIejEnRpCYgKrAMQOcD4Wrhti86uXXwyyjrhXaZI18XSgqG7AD5ucsDhYrKo3af9mHJ3KoG4ZDLeBJFOar6k4ARMbfPWQMLKRu1WnQ6dNhf6sWSWQptwW0kbuhMsYnX8Kk77IINHgsjPaRp0yjAwHoy2_3dLcR5CkHEceaXZ1EGiRMqReiEvT8YcbRX7mZj4V3XnmiF19baN9BTGXGImdf1AuXkuEbvthkwYi2NlnO1HbROG2_ZsUHnFEjT3uSU_tQhoV7_dFnIoXDM7G9kkC7dqzVvSSJRLzSQtTl90HhIqt5q2-tvHx0F-DNvOzVlxtR1z4_I_bk84HhL_3gV
