name: Typeorm UML
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
          - 12.x
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          CI: true
      - name: Build project
        run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout typeorm-uml
        uses: actions/checkout@v2
      - name: Checkout typeorm/typescript-example
        uses: actions/checkout@v2
        with:
          repository: typeorm/typescript-example
          path: example
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies and build typeorm-uml
        run: |
          npm ci --ignore-scripts
          npm run build
        env:
          CI: true
      - name: Install dependencies and build typeorm/typescript-example
        working-directory: example
        run: |
          npm i
          npx tsc
      - name: Test uml diagram
        working-directory: example
        run: test "$(../bin/run)" = "$EXPECTED"
        env:
          EXPECTED: http://www.plantuml.com/plantuml/png/XP71QiCm44Jl-nLRUh5eGqaX5sDCJ6XeBZq4KteBShHDH6p9I5kmgVFlbTqaKDEqkcbdtym8pJrBnnzL2N2Zw5qRmlf0RTG8J8gqIHwAz2AmB4hg5JAikSK6amIZ_FvskSp24PYc07kj23sJ8yjjJVvxK17lhV80R6jaYuLbjXKgxMZBsXhm1srgwMI5POZgIRGkC84OKd4hcNRMjIZm4n3lXfQe5OeOLozvD9sAC3QoeXXVi_NYELj7ZxEPWEF5ehQU_yR3iyen7wRKS8pvqri-CjkSIcdocz_xzLkhKSX9EWC_vH1mrVdOJIPTDtZ-ktI-0yp9gFv_lm00
